#Api gateway configuration....
spring:
  cloud:
    gateway:
      routes:
        - id: USER-SERVICE-MS
          uri: lb://USER-SERVICE-MS
          predicates:
            - Path=/users/**
        - id: HOTEL-SERVICE-MS
          uri: lb://HOTEL-SERVICE-MS
          predicates:
            - Path=/hotels/**,/staffs/**  #- Path=/**  Sare URL ke liye
        - id: RATING-SERVICE-MS
          uri: lb://RATING-SERVICE-MS
          predicates:
            - Path=/ratings/**